# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Developer portfolio of Eli Tallman
email: eli.tallman02 ÇT gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Enlighten your mind reading my musings, browsing my projects, and discovering hidden easter eggs.
  Why won't this text show up?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elitallman.com.com" # the base hostname & protocol for your site
twitter_username: elitallman
github_username:  elitallman

# Build settings
markdown: kramdown
